theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - admin.md
  - public.md
  - help/index.md
  - help/api.md
  - help/variables.md
  - help/shortcodes.md
  - help/html.md
